### PR TITLE
Sync with prometheus/prometheus to `b6f903b5f` (2023-09-01)

### PR DESCRIPTION
**Pull request by dimitarvdimitrov**
There are a lot of changes in prometheus, some notable changes are
* https://github.com/grafana/mimir-prometheus/commit/3c80963e8102b9baaffb10dd76db9c9bfcd1c077 which mmaps head chunks in the background insteaed of on the append path
* https://github.com/grafana/mimir-prometheus/commit/8ef7dfdeebf0a7491973303c7fb6b68ec5cc065b which sets a 1KiB size limit on all chunks (in addition to the 120-sample limit)
* https://github.com/grafana/mimir-prometheus/commit/54aaa2bd7e9dad6a0eae34232b95b82dc7143059 which adds two new promQL functions for native histograms - `histogram_stdvar` and `histogram_stddev`

### CODE REVIEW

**Comment by dimitarvdimitrov** [comment]
This has been running in dev clusters since Monday/Saturday and there are no signs of corrupted data or changed resources usage. Hence, I'm making this as ready for review

**Review by pstibrany — APPROVED** [review]
I don't see any conflicting changes related to our customizations, so approving this.

**Comment by dimitarvdimitrov** [comment]
to make reviewing the conflict resolution you can locally run `git show 77ac7ad40a3781a552adb97ffe052595aac7d84e --remerge-diff` to show only the diff from the conflict resolution changes

**Review by krajorama — APPROVED** [review]
Seems safe to merge. I've scanned through the code and I don't think we have semantic conflicts.

**Pull request merged**
