### PR TITLE
Sync with upstream Prometheus

### PR DESCRIPTION
**Pull request by codesome**
Gets https://github.com/prometheus/prometheus/pull/11992

### CODE REVIEW

**Comment by codesome** [comment]
The lint fail (which failed on building tsdb tests) showed that the unit tests are not in sync with upstream. It might mostly be the OOO tests since it was first written here and then ported. Possibly something to verify in the future but not critical.

**Comment by pracucci** [comment]
@codesome What's about this failing test?

```
--- FAIL: TestChunkDiskMapper_WriteUnsupportedChunk_Chunk_IterateChunks (0.01s)
    head_chunks.go:894: 
        	Error Trace:	/home/runner/work/mimir-prometheus/mimir-prometheus/tsdb/chunks/head_chunks_test.go:201
        	            				/home/runner/work/mimir-prometheus/mimir-prometheus/tsdb/chunks/head_chunks.go:894
        	            				/home/runner/work/mimir-prometheus/mimir-prometheus/tsdb/chunks/head_chunks_test.go:194
        	Error:      	Not equal: 
        	            	expected: 0xc1
        	            	actual  : 0x41
        	Test:       	TestChunkDiskMapper_WriteUnsupportedChunk_Chunk_IterateChunks
```

**Comment by pracucci** [comment]
Please hold on before merging this PR, cause I would like to merge it after https://github.com/grafana/mimir-prometheus/pull/458.

**Comment by codesome** [comment]
Should be fixed now. `UnsupportedMask` was `0b11000000`, while the out-of-order was already using the first bit for out-of-order. Since it is only used in tests, I changed `UnsupportedMask` to `0b01000000`. Now ChunkDiskMapper treats the last 7 bits as the chunk encoding and the first bit for OOO information.

**Comment by pracucci** [comment]
Ok, merging with merge commit 🚀

**Pull request merged**
