### PR TITLE
Merging remotes/prometheus/main into origin/main

### PR DESCRIPTION
**Pull request by duricanikolic**
In order to proceed with Issue [1040](https://github.com/grafana/mimir-squad/issues/1040) I need to get [https://github.com/prometheus/prometheus/pull/12066](https://github.com/prometheus/prometheus/pull/12066).
Hence, it is needed to synchronize `mimir-prometheus` with `prometheus`.

### CODE REVIEW

**Review by pstibrany — APPROVED** [review]
Please don't forget to merge with regular Merge commit, instead of Squash & Merge.

**Review by pracucci — APPROVED** [review]
Took a while to review, but LGTM. I double checked commits and they're all in. I also checked the commits to fix conflicts and I haven't noticed anything unexpected. 🤞

**Comment by pstibrany** [comment]
> Took a while to review, but LGTM. 

Isn't it a waste of time to do extensive review of PRs that were already reviewed in upstream prometheus? (Not speaking of conflict fixes of course)

For Mimir important part is only what's used in mimir, and we get to see those important bits when updating `mimir-prometheus` in Mimir.

**Comment by pracucci** [comment]
> Isn't it a waste of time to do extensive review of PRs that were already reviewed in upstream prometheus? 

I reviewed that all commits are there (since they were cherry-picked 1-by-1) and I've reviewed the commits to fix conflicts.

**Comment by pstibrany** [comment]
> I reviewed that all commits are there (since they were cherry-picked 1-by-1) and I've reviewed the commits to fix conflicts.

👍 Fair enough. It sounded like you did a review of all changes to me :)

**Pull request merged**
