### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by aknuds1**
Sync with Prometheus upstream main branch ([e2e01c1](https://github.com/prometheus/prometheus/tree/e2e01c1cffbfc4f26f5e9fe6138af87d7ff16122)). My method was to list all the commits added to upstream's main branch after the last merge, and merge every single one of them, resolving conflicts per commit as necessary.

There were difficult merge conflicts in the following files/commits, and I could use help making sure they're done correctly in retrospect:

* tsdb/head_append.go:
  * 14e3c05ce
model/labels/regexp_test.go:
  * bb47f7892
  
Included commits:

* 458613bf7 Merge pull request #14846 from prometheus/dependabot/go_modules/github.com/envoyproxy/go-control-plane-0.13.0
* 1ed25d5f9 Merge pull request #14843 from prometheus/dependabot/go_modules/github.com/scaleway/scaleway-sdk-go-1.0.0-beta.30
* d4e1900b4 Merge pull request #14845 from prometheus/dependabot/go_modules/golang.org/x/oauth2-0.23.0
* 55ed6f3a1 Merge pull request #14840 from prometheus/dependabot/go_modules/golang.org/x/tools-0.24.0
* 788d8c2bc Merge pull request #14839 from prometheus/dependabot/go_modules/github.com/prometheus/common-0.59.0
* 1a179183f Merge pull request #14786 from prometheus/dependabot/go_modules/documentation/examples/remote_storage/github.com/prometheus/client_golang-1.20.2
* 404e57703 Merge pull request #14734 from roidelapluie/scrape_failure_logger
* 59402f8ab Merge pull request #14841 from prometheus/dependabot/go_modules/github.com/prometheus/exporter-toolkit-0.12.0
* 8805301f5 Merge pull request #14851 from prometheus/dependabot/go_modules/github.com/prometheus/common-0.59.1
* 5a1f4a776 Merge pull request #14842 from prometheus/dependabot/go_modules/github.com/digitalocean/godo-1.122.0
* a7a9dbaf1 Merge pull request #14837 from prometheus/dependabot/go_modules/go-opentelemetry-io-14eb93439b
* 51e8b6f21 Merge pull request #14832 from prometheus/dependabot/go_modules/golang.org/x/text-0.18.0
* f44304a6b Merge pull request #14804 from prometheus/dependabot/go_modules/github.com/linode/linodego-1.40.0
* 828f340aa Merge pull request #14791 from prometheus/dependabot/go_modules/github.com/miekg/dns-1.1.62
* edc83ed16 Update storage.md with the latest around Remote Write 2.0 (#14848)
* cb671ef23 Merge pull request #14788 from prometheus/dependabot/go_modules/k8s-io-a0fc09b0c0
* 9f57f14d6 Merge pull request #14803 from prometheus/dependabot/go_modules/github.com/docker/docker-27.2.0incompatible
* db5e48dc3 promql.Engine.Close: No-op if nil (#14861)
* 4fc562f9e OTLP: Support context cancellation/timeout during translation (#14612)
* 09c1e0b14 Limit memory usage Go tests with race detector (#14862)
* d2899000c Merge pull request #14872 from prometheus/mantine-ui
* ab5994da0 Merge pull request #14874 from krajorama/fix-panic-in-ooo-query2
* 16e5e9954 Merge pull request #14767 from bboreham/fix-encoding-comment
* 6c7968933 Merge pull request #14875 from prometheus/move-am-sd-menu-entry
* 43cf9ad7d Merge pull request #14852 from roidelapluie/testqvalue
* 1b281f074 Bump @types/node from 22.5.2 to 22.5.4 in /web/ui (#14873)
* be0c0bd84 Fix error flood by downgrading OTel dependencies (#14884)
* a6346184f Merge pull request #14881 from rfratto/remove-rfratto-maintainer
* 7741134c0 Merge pull request #14888 from roidelapluie/fix-discovered-alertmanagers
* bde509247 Merge pull request #14882 from prometheus/new-ui-help-button
* 3ce285e0a Merge pull request #14891 from roidelapluie/fix-lookback-delta
* 482f1f608 Merge pull request #14880 from prometheus/njpm/fix-utf8-config
* 8114f9a28 Merge pull request #14821 from charleskorn/nh-negative-multiplication-division
* 8d3da31f8 Merge pull request #14885 from prometheus/superq/update_promci_2
* 1bd10ac5d Merge pull request #14893 from roidelapluie/bottomkui
* ad652de29 Merge pull request #14895 from prometheus/fix-limit-ratio-explain
* 4e1716610 Merge pull request #14896 from jan--f/release-3.0-beta.0
* 54772a2c8 Bump actions/upload-artifact from 4.3.4 to 4.4.0 (#14775)
* 50cd453c8 chore: Fix typos (#14868)
* 4f81e077b Upgrade github.com/googleapis/enterprise-certificate-proxy to v0.3.4 (#14897)
* 5aa3d8260 TSDB: OOO native histograms: prep for multiple ooo head chunks (#14850)
* 73e94dc9f Merge pull request #14899 from SuperSandro2000/patch-1
* b93ed7bd1 Merge pull request #14898 from prometheus/fix-targets-page-coloring
* e8fa1312a Merge pull request #14903 from jan--f/drop-agent-ff-docs
* 62bd893b8 Merge pull request #14907 from prometheus/julius/new-ui-improvements
* 31ce9dacf Merge pull request #14901 from roidelapluie/prebuiltui
* d67ba3ed3 Merge pull request #14908 from roidelapluie/fix14889
* f007659f0 Merge pull request #14531 from prometheus/dependabot/go_modules/github.com/go-zookeeper/zk-1.0.4
* 6febfbb3b put back feature flag 'delayed-compaction' and 'old-ui' (#14909)
* 6acd3dee5 Merge pull request #14913 from prometheus/explain-view-set-ops
* b6015e7c7 Add support for running govulncheck (#12654)
* 2c87817e4 Merge pull request #14914 from prometheus/julius/new-ui-improvements
* 919dc0cbc storage: Update LabelQuerier interface to return sorted label values (#14849)
* 14e3c05ce tsdb: Add support for ingestion of out-of-order native histogram samples  (#14546)
* d5f4fabd1 Merge pull request #14911 from bboreham/clarify-postings-benchmark
* 00d23c968 Merge pull request #14915 from prometheus/dependabot/npm_and_yarn/web/ui/typescript-5.6.2
* d1b4312f0 fix(wlog/watcher_test.go): make TestRun_AvoidNotifyWhenBehind more resilient
* d0d57ff64 [DOC] Add username_file in basic auth http client config (#12749)
* d90d0976b fix(bstream/writeByte): ensure it appends only one byte (#14854)
* 6c5e2f8fb Merge pull request #12829 from arukiidou/chore/bump-webui
* b8d1336d4 Merge pull request #14912 from roidelapluie/notready
* c328d5fc8 fix rwv2 build write request benchmark, also change how the memory usage (#14925)
* bb47f7892 Merge pull request #14505 from marioferh/improve_performance_regex
* b6107cc88 Make rate possible non-counter annotation consistent (#14910)
* c36589a6d Merge pull request #14940 from roidelapluie/subsecondzoom
* c7fb6188b Merge pull request #14930 from jan--f/holt-winters-experimental
* df9916ef6 Merge pull request #14677 from prometheus/beorn7/histogram
* e480cf21e Merge pull request #14931 from prometheus/nexucis/autocomplete-topl
* 005bd33fe support v2 proto for BenchmarkSampleSend (#14935)
* 5b9148e55 Merge pull request #14820 from charleskorn/promqltest-native-histogram-format
* 921525222 [BUGFIX] TSDB: Only query chunks up to truncation time (#14948)
* ca18f298e Merge pull request #14949 from Maniktherana/minor-fixes-ct
* d42232e17 Merge pull request #14932 from bboreham/chunk-xor-combine-writebits
* dfc6f4b5b Merge pull request #14945 from roidelapluie/submillis
* 52fe4cc4e Merge pull request #14944 from roidelapluie/copy
* 6bcb064d9 Merge pull request #14950 from Maniktherana/fuzz-om-minor-change
* 31c576055 Neater string vs byte-slice conversions (#14425)
* 919648caf Merge pull request #14947 from roidelapluie/reloadinvalidyaml
* f179cb948 chore: bump client_golang from 1.20.3 to 1.20.4 (#14963)
* faf5ba29b Merge pull request #14959 from prometheus/merge-2.55-into-main
* c2bbabb4a promql.Engine: Refactor vector selector evaluation into a method (#14900)
* a0f26febc Merge pull request #12180 from damnever/perf/relabel-add-label
* 67caa03dc Merge pull request #14970 from prometheus/beorn7/doc
* 5037cf75f Merge pull request #14972 from prometheus/jvp/make-mantime-ui-assets-relative
* 5d8f0ef0c Merge pull request #14721 from bboreham/exp-grow-postings
* 751100b3d Merge pull request #12998 from ringerc/docs-instant-vector-staleness
* 5710ddf24 [ENHANCEMENT] Alerts: remove metrics for removed Alertmanagers (#13909)
* d5f65cfce Merge pull request #14694 from prometheus/ct-histogram
* 79a6238e1 scrape/scrape_test.go: reduce the time it takes to reload the manager (#14447)
* f74722841 Merge pull request #14160 from alex-kattathra-johnson/issue-13959
* 5f26d86da Merge pull request #14982 from prometheus/fix-remove-defunct-alert-close-buttons
* 410fcce6f Remove unnecessary pprof import (#14988)
* 7aa472137 Merge pull request #14946 from roidelapluie/notifications
* 105ab2e95 fix(test): adjust defer invocations (#14996)
* 54de4fb78 Merge pull request #14975 from colega/process-mempostings-delete-with-gomaxprocs-workers
* 537c5dbbc Merge pull request #14994 from roidelapluie/notifications2
* 97f321915 test(discovery): add a Configs test showing that the custom unmarshalling/marshalling is broken.
* b5569c407 fix(discovery): adjust how type is retrieved in Configs' MarshalYAML/UnmarshalYAML
* b826c4398 Calculate path prefix directly in initial settings Redux value (#14981)
* 9bb7fab4a remove LeviHarrison as default maintainer (#15005)
* d4423b192 Merge pull request #14992 from bboreham/remove-stubs
* 7a90d73fa sd k8s: test for sidecar container support in endpoints
* a10dc9298 sd k8s: support sidecar containers in endpoint discovery
* 73997289c tests: update discovery tests with new labael
* 77d3b3aff OTLP: Remove experimental word form OTLP receiver (#14894)
* c5c2566b8 MAINTAINERS: Add Arthur as an otlptranslator maintainer (#15024)
* 4cb5f23c3 api: Improve doc comments for v1.MinTime and v1.MaxTime (#14986)
* d745e762b Merge pull request #15048 from prometheus/dependabot/npm_and_yarn/web/ui/mantine/dates-7.13.1
* f1f63a19a Merge pull request #15044 from prometheus/dependabot/npm_and_yarn/web/ui/react-router-dom-6.26.2
* 885138861 Merge pull request #15041 from prometheus/dependabot/npm_and_yarn/web/ui/vitest-2.1.1
* c43da57a2 Merge pull request #15051 from prometheus/dependabot/npm_and_yarn/web/ui/types/lodash-4.17.9
* 357e64dbe Merge pull request #15050 from prometheus/dependabot/npm_and_yarn/web/ui/eslint-plugin-react-refresh-0.4.12
* 72a0d2cb3 Merge pull request #15047 from prometheus/dependabot/npm_and_yarn/web/ui/codemirror/view-6.34.1
* 4d4fe3c78 Merge pull request #15066 from prometheus/dependabot/github_actions/scripts/actions/checkout-4.2.0
* 764b1227b Merge pull request #15067 from prometheus/dependabot/github_actions/github/codeql-action-3.26.10
* 45efd0176 Merge pull request #15052 from prometheus/dependabot/npm_and_yarn/web/ui/uiw/react-codemirror-4.23.3
* 1b856bbe8 Merge pull request #15037 from prometheus/dependabot/npm_and_yarn/web/ui/jsdom-25.0.1
* afbe72f7b Merge pull request #15068 from prometheus/dependabot/github_actions/bufbuild/buf-setup-action-1.43.0
* 889588317 Merge pull request #15053 from prometheus/dependabot/npm_and_yarn/web/ui/mantine/notifications-7.13.1
* 668522225 Merge pull request #15054 from prometheus/dependabot/npm_and_yarn/web/ui/tanstack/react-query-5.59.0
* cb895264a Merge pull request #15060 from prometheus/dependabot/npm_and_yarn/web/ui/mantine/code-highlight-7.13.1
* 26058254a Merge pull request #15062 from prometheus/dependabot/npm_and_yarn/web/ui/eslint/js-9.11.1
* 64c990937 Merge pull request #15063 from prometheus/dependabot/npm_and_yarn/web/ui/types/jest-29.5.13
* 05668c592 Merge pull request #15059 from prometheus/dependabot/npm_and_yarn/web/ui/vite-5.4.8
* fad9859d5 Merge pull request #15065 from prometheus/dependabot/github_actions/actions/setup-node-4.0.4
* 9c0fe8e45 Merge pull request #15057 from prometheus/dependabot/npm_and_yarn/web/ui/codemirror/autocomplete-6.18.1
* e32dbeb38 Merge pull request #15056 from prometheus/dependabot/npm_and_yarn/web/ui/eslint-9.11.1
* 8fe5f36a3 Merge pull request #15058 from prometheus/dependabot/npm_and_yarn/web/ui/tabler/icons-react-3.19.0
* 4edbe3f70 Merge pull request #15055 from prometheus/dependabot/npm_and_yarn/web/ui/globals-15.10.0
* bcd9ce1d4 Merge pull request #15061 from prometheus/dependabot/npm_and_yarn/web/ui/postcss-8.4.47
* 98cd80b2e feat: add microbenchmarks for OM CT parsing (#14933)
* e99e7ca9c README: Update readme with API flag change for the otlp receiver (#15073)
* f1c57a95e change: No longer ingest OM _created as timeseries if feature-flag 'enable-ct-zero-ingestion' is enabled; fixed OM text CT conversion bug (#14738)
* 78f792135 Merge pull request #15025 from prometheus/notreset-bug
* e1f8a7914 Merge pull request #15069 from prometheus/allow-blank-issues
* 20bf32b9d Merge pull request #15074 from jadolg/synchronized-RandomUnprivilegedPort
* 199d2fb49 Merge pull request #14989 from NeerajGartia21/eval_info
* 3a8131b3f Merge pull request #15032 from prometheus/dependabot/go_modules/go-opentelemetry-io-449d04d146
* 34c0f2d48 Merge pull request #15029 from prometheus/dependabot/go_modules/documentation/examples/remote_storage/github.com/prometheus/common-0.60.0
* d98c37478 Merge pull request #15035 from prometheus/dependabot/go_modules/google.golang.org/api-0.199.0
* 023146e91 Merge pull request #15082 from roidelapluie/notifystart
* 47aeca966 feat: naive fixes and optimzations for `CreatedTimestamp` function (#14965)
* 297667469 Merge pull request #15090 from roidelapluie/querylogrule
* 4fc7b881a Merge pull request #15046 from prometheus/dependabot/go_modules/github.com/linode/linodego-1.41.0
* a1c2f59bc Merge pull request #15096 from prometheus/notification-style-cleanups
* ab64966e9 fix: use "ErrorContains" or "EqualError" instead of "Contains(t, err.Error()" and "Equal(t, err.Error()" (#15094)
* 5a54ae67e Bump actions/checkout from 4.1.6 to 4.2.0 (#15064)
* 989db7bc3 Merge pull request #15042 from prometheus/dependabot/go_modules/go.uber.org/automaxprocs-1.6.0
* 8d281c349 textparse: Refactored benchmark (#15083)
* 9d8f93ea9 Merge pull request #15113 from yeya24/add-missing-allow-overlapping-compaction-flag
* b3f60196c Merge pull request #15039 from prometheus/dependabot/go_modules/google.golang.org/grpc-1.67.1
* a42e8473a Merge pull request #15043 from prometheus/dependabot/go_modules/golang.org/x/tools-0.25.0
* 1df86df17 Merge pull request #15117 from prometheus/dependabot/go_modules/golang.org/x/tools-0.26.0
* 2b4ca9824 Merge pull request #15038 from prometheus/dependabot/go_modules/github.com/gophercloud/gophercloud-1.14.1
* f6e110d58 textparse: Refactored main testing utils for reusability; fixed proto Units. (#15095)
* 65f610353 Merge pull request #15118 from roidelapluie/notificationsdoc
* 805954d8f Merge pull request #14906 from tjhop/chore/3.0-adopt-slog
* 24caa3653 Merge pull request #15040 from prometheus/dependabot/go_modules/github.com/digitalocean/godo-1.126.0
* e5f604eb9 Merge pull request #15045 from prometheus/dependabot/go_modules/github.com/klauspost/compress-1.17.10
* 7b6259b29 Merge pull request #15127 from roidelapluie/assets
* 576000a45 Merge pull request #15111 from prometheus/beorn7/doc
* 663a66b52 Merge pull request #11224 from dekimsey/consul-catalog-filter-support
* 8650d2580 Add additional basic nhcb unit tests (#15086)
* 90f783244 Merge pull request #15084 from hvnsweeting/patch-1
* 5e987e7c7 Merge pull request #15092 from jan--f/clarify-storage-contract
* 02d0de998 Merge pull request #14997 from fionaliao/fl/update-format-docs
* 720a2599a Merge pull request #15135 from prometheus/beorn7/docs
* 8b545bab2 Merge pull request #15026 from huochexizhan/main
* 032ca9ef9 [PERF] textparse: further optimzations for OM `CreatedTimestamps` (#15097)
* d9a54284f Merge pull request #14987 from machine424/yafix
* e6f9e2dde Merge pull request #15119 from roidelapluie/dochttp
* 50ef0dc95 Fix `MemPostings.Add` and `MemPostings.Get` data race (#15141)
* 1e3953ab1 Bump github.com/docker/docker (#15033)
* 7ce9cfa6e Bump the k8s-io group with 3 updates (#15030)
* 16bba78f1 discovery: Improve Azure test coverage to 50% (#14586)
* b8867f8ea Merge pull request #15142 from krajorama/fix-appendhistogram-race
* c3b8582cf [PERF] textparse: optimize OM `p.isCreatedSeries()` (#15150)
* 522149a2a model: move classic NHCB conversion into its own file (#15156)
* 911c3efb9 Merge pull request #14976 from prometheus/prep-3.0-beta.1
* 1e1f6ab9d Merge pull request #15120 from bboreham/floor-ino-mint
* d4b1f9eb3 Corrects the behaviour of binary opperators between histogram and float (#14726)
* 55419275a Merge pull request #15159 from prometheus/nhcb-scrape-optimize1
* 08a716250 discovery: aws/ec2 unit tests (#14364)
* 5a4e4f693 Fix stddev/stdvar when aggregating histograms, NaNs, and infinities (#14941)
* 5dd5aec0e Merge pull request #14599 from machine424/sigsegv
* 6ce21b839 Merge pull request #15172 from krajorama/update-client-golang
* 2cabd1b70 config: remove expand-external-labels flag in release 3.0 (#14657)
* efc43d071 s/scrape_classic_histograms/always_scrape_classic_histograms (3.0 breaking change) (#15178)
* 763cbdf35 Merge pull request #15180 from prometheus/ooo-nh-corrupt-chunk
* 754c104a3 Merge pull request #15173 from prometheus/merge-2.55-into-main-3
* c78d5b94a Disallowing configure AM with the v1 api (#13883)
* 5505c83a4 Merge pull request #15167 from machine424/impor
* 421a3c22e scrape: provide a fallback format (#15136)
* 98dcd28b1 Merge pull request #15170 from machine424/awldi
* d8c160593 Merge pull request #15164 from machine424/quantile
* 6b36a5592 Merge pull request #14618 from machine424/para
* 70e2d2302 Merge pull request #11474 from clwluvw/group-label
* d2802c6fa api: Add rule group pagination to list rules api (#14017)
* ad4857de5 Merge pull request #14978 from prometheus/nhcb-scrape-impl
* 1b4e7f74e feat(tools): add debug printouts to rules unit testing (#15196)
* 3bb5e28c6 Merge pull request #15197 from prometheus/alexg/docs-issue-11570
* aa81210c8 NHCB scrape: refactor state handling and speed up scrape test (#15193)
* 7c7116fea Merge pull request #15176 from jhesketh/jhesketh/round
* cccbe7251 TSDB: Fix some edge cases when OOO is enabled (#14710)
* 2182b8327 feat(nhcb): implement created timestamp handling (#15198)
* 469573b13 fix(nhcb): do not return nhcb from parse if exponential is present (#15209)
* 3cb09acb2 Docs: Remove experimental note on out of order feature (#15215)
* 07d01a9e0 Merge pull request #15219 from jan--f/rw-default-http2-off
* 24a10528a Merge pull request #15205 from tjhop/chore/slog-fixes
* f131cdd4c 3.0 migration guide (#15099)
* 42a30a0c4 Merge pull request #15217 from CharlieTLe/support-int-exemplars
* 93db81dd3 Merge pull request #14983 from machine424/dopp
* 372b83d7b Documented that WAL can still be written after memory-snapshot-on-shutdown (#15179)
* bab587b9d Agent: allow for ingestion of CT samples (#15124)
* eb3b34902 fix(nhcb): created timestamp fails when keeping classic histograms (#15218)
* 685d6d169 refactor: reorder fields in defaultSDConfig initialization for consistency
* 7cda23ba3 fix(lezer-promql): fix missing types export in package.json (#15161)
* 99c0e6801 Merge pull request #15230 from GiedriusS/optimize_resolvepodref
* 559722dc6 Merge pull request #15206 from multani/fix-doc-formatting
* 706dcfeec tsdb.CircularExemplarStorage: Avoid racing (#15231)
* 350e0d5bc Merge pull request #15228 from shenpengfeng/main
* b6c538972 [REFACTORY] simplify appender commit (#15112)
* d0eecb122 Merge pull request #15239 from colega/revert-14975-process-mempostings-delete-with-gomaxprocs-workers
* 284135a90 Merge pull request #15223 from jan--f/release-3.0.0-rc.0
* ccaff318f Merge pull request #15249 from prometheus/otlp-fix-sanitiza
* dd4eb4590 Merge pull request #15222 from jmichalek132/jm-add-tcp-events-to-tracing
* e2e01c1cf Merge pull request #15216 from yeya24/log-last-series-labels

### CODE REVIEW

**Review by bboreham — APPROVED** [review]
I scanned all diffs between mimir-prometheus and upstream prometheus after this PR, and didn't spot any errors.
Also looked specifically at `tsdb/head_append.go` and `model/labels/regexp_test.go`.

**Review by krajorama — APPROVED** [review]
LGTM
Only noteworthy thing to me beside the regex matching change that we know about is the fact that this PR renames holt_winters PromQL function.

**Comment by colega** [comment]
We should create an alias for `holt_winters` in Mimir.

**Comment by aknuds1** [comment]
> We should create an alias for holt_winters in Mimir.

Doing that in https://github.com/grafana/mimir-prometheus/pull/743.

**Comment by colega** [comment]
We don't really need to do that here in `mimir-prometheus`, IMO, it's a Mimir requirement, so should be done there.

**Comment by aknuds1** [comment]
> We don't really need to do that here in mimir-prometheus, IMO, it's a Mimir requirement, so should be done there.

@colega how can we do it in Mimir?

**Comment by colega** [comment]
You can do it in Mimir through:
```go
func init() {
	parser.Functions["holt_winters"] = parser.Functions["double_exponential_smoothing"]
	promql.FunctionCalls["holt_winters"] = promql.FunctionCalls["double_exponential_smoothing"]
}
```

**Comment by aknuds1** [comment]
@colega hm yeah, maybe it is that simple. I'll check.

**Review by bboreham — APPROVED** [review]

**Pull request merged**
