### PR TITLE
Sync prometheus

### PR DESCRIPTION
**Pull request by pracucci**
Re-sync upstream Prometheus, fixing conflicts introduced by https://github.com/prometheus/prometheus/pull/12946.

### CODE REVIEW

**Comment by pracucci** [comment]
Could be blocked by https://github.com/prometheus/prometheus/pull/13509

**Comment by pracucci** [comment]
> Could be blocked by [prometheus/prometheus#13509](https://github.com/prometheus/prometheus/pull/13509)

Yes, that PR introduced a severe corruption bug. We should wait to re-sync until https://github.com/prometheus/prometheus/pull/13509 is merged.

**Comment by pracucci** [comment]
> > Could be blocked by [prometheus/prometheus#13509](https://github.com/prometheus/prometheus/pull/13509)
> 
> Yes, that PR introduced a severe corruption bug. We should wait to re-sync until [prometheus/prometheus#13509](https://github.com/prometheus/prometheus/pull/13509) is merged.

https://github.com/prometheus/prometheus/pull/13509 was merged and I've re-synced on top of `main`.

**Review by krajorama — APPROVED** [review]
Cannot speak to the rule eval change, but the new histogram_avg function was reviewed by me primarily, looks unchanged here. The reuseOrGetF/HPointSlices seems to be  a layer over the float/histogram sample model, so should be good from my point of view.

**Comment by pracucci** [comment]
> Cannot speak to the rule eval change

I did that change, so I feel quite comfortable with the conflict resolution. To be clear, only ruler got conflicts.

**Pull request merged**
