### PR TITLE
Remove old chunk mapper.

### PR DESCRIPTION
**Pull request by pstibrany**
This PR removes `OldChunkDiskMapper`

### CODE REVIEW

**Review by pracucci — APPROVED** [review]

**Comment by pstibrany** [comment]
@codesome  I've removed old chunk mapper in this PR, but now `TestOOOCompaction` and `TestOOOCompactionFailure` are failing. It turns out that old chunk mapper was used by default instead of new chunk mapper (which is also in upstream Prometheus).

Would you please take a look at the failing tests? There seem to be small difference between old and new chunk mapper. I'll try to look at it as well, but you may have better idea about the differences between old and new chunk mapper (perhaps just the fact that new one is async is enough change to cause this).

**Comment by pstibrany** [comment]
> @codesome I've removed old chunk mapper in this PR, but now `TestOOOCompaction` and `TestOOOCompactionFailure` are failing. It turns out that old chunk mapper was used by default instead of new chunk mapper (which is also in upstream Prometheus).
> 
> Would you please take a look at the failing tests? There seem to be small difference between old and new chunk mapper. I'll try to look at it as well, but you may have better idea about the differences between old and new chunk mapper (perhaps just the fact that new one is async is enough change to cause this).
> 
> Failures: https://github.com/grafana/mimir-prometheus/runs/7728655169?check_suite_focus=true

Fix is likely available in https://github.com/prometheus/prometheus/pull/11075.

**Comment by codesome** [comment]
https://github.com/prometheus/prometheus/pull/11075 is same as the one in mimir-prometheus, and tests might fail for async queue there as well I think. In Prometheus the queue is disabled by default I believe. I will take a look at those tests in coming days.

**Comment by codesome** [comment]
The last commit should fix the tests. I will merge on green (minus the unrelated lint failure)

**Comment by pstibrany** [comment]
Thanks @codesome, much appreciated! I can take care of updating mimir-prometheus in Mimir as a next step.

**Comment by codesome** [comment]
Another test failure because of some sorting issue. On it.

**Pull request merged**
